seed: 2137
datasets:

  stroke:
    path: /Users/wciezobka/sano/projects/masters-thesis/Datasets/NeuroFlicksRCC/networks
    channel: 0
    preprocessing:
      undirected: False
      connection_weight_threshold: !!python/tuple [0.6, -0.6]
      subtract_control_mean: True
    models:

      GCN:
        holdout_size: 0.2
        hyperparameters:
          ldp_features: True
          learning_rate: 0.005
          epochs: 150
