seed: 54321
datasets:

  stroke:
    path: /Users/wciezobka/sano/projects/masters-thesis/Datasets/NeuroFlicksRCC/networks
    channel: 0
    preprocessing:
      undirected: False
      connection_weight_threshold: !!python/tuple [0.8, 0.995]
    models:

      GCN:
        holdout_size: 0.2
        hyperparameters:
          ldp_features: True
          learning_rate: 0.001
          epochs: 150

      LTP:
        folds: 10
        hyperparameters:
          log_degree: True

      Graph2Vec:
        folds: 10
        hyperparameters:
          wl_iterations: 2
          dimensions: 32
          epochs: 200

  synthetic:
    path: /Users/wciezobka/sano/projects/masters-thesis/Datasets/Synthetic/ScaleFreeBias/networks
    preprocessing:
      undirected: False
    models:

      GCN:
        holdout_size: 0.2
        hyperparameters:
          ldp_features: True
          learning_rate: 0.005
          epochs: 100

      LTP:
        folds: 10
        hyperparameters:
          log_degree: True

      Graph2Vec:
        folds: 10
        hyperparameters:
          wl_iterations: 2
          dimensions: 32
          epochs: 200
